services:

  # ------------------------
  # NabedSyria
  # ------------------------

  nsyidentity:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nsyidentity
    environment:
      - SERVICE_KEY=IDENTITYNSY
      - APP_SECRETS_FILE=/run/secrets/app_secrets
      - IDENTITYNSY_OPENIDDICT_ISSUER=https://nsyuser.i-myapp.com
      - ASPNETCORE_ENVIRONMENT=Production
      - IS_DOCKER=true
      - ASPNETCORE_URLS=http://+:8080
    
    ports:
      - "5015:8080"
    secrets:
      #- db_connection
      - app_secrets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nsyidentity.rule=Host(`nsyuser.i-myapp.com`)"
      - "traefik.http.routers.nsyidentity.entrypoints=websecure"
      - "traefik.http.routers.nsyidentity.tls.certresolver=myresolver"
      - "traefik.http.services.nsyidentity.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.nsyidentity-headers.headers.customrequestheaders.X-Forwarded-Host=nsyuser.i-myapp.com"
    networks:
      - NSY_network
    restart: always

    # ------------------------
  # Sultan
  # ------------------------

  nidentity:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nidentity
    environment:
      - SERVICE_KEY=IDENTITYNSULTAN
      - APP_SECRETS_FILE=/run/secrets/app_secrets
      - IDENTITYNSULTAN_OPENIDDICT_ISSUER=https://nuser.i-myapp.com
      - ASPNETCORE_ENVIRONMENT=Production
      - IS_DOCKER=true
      - ASPNETCORE_URLS=http://+:8080
    
    ports:
      - "5011:8080"

    secrets:
      - app_secrets

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nidentity.rule=Host(`nuser.i-myapp.com`)"
      - "traefik.http.routers.nidentity.entrypoints=websecure"
      - "traefik.http.routers.nidentity.tls.certresolver=myresolver"
      - "traefik.http.services.nidentity.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.nidentity-headers.headers.customrequestheaders.X-Forwarded-Host=nuser.i-myapp.com"
    networks:
      - Sultan_network
    restart: always
    
    # ------------------------
    # Secba
    # ------------------------

  sidentity:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: sidentity
      environment:
        - SERVICE_KEY=IDENTITYSECBA
        - APP_SECRETS_FILE=/run/secrets/app_secrets
        - IDENTITYSECBA_OPENIDDICT_ISSUER=https://suser.i-myapp.com
        - ASPNETCORE_ENVIRONMENT=Production
        - IS_DOCKER=true
        - ASPNETCORE_URLS=http://+:8080

      ports:
        - "5501:8080"

      secrets:
        - app_secrets

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sidentity.rule=Host(`suser.i-myapp.com`)"
        - "traefik.http.routers.sidentity.entrypoints=websecure"
        - "traefik.http.routers.sidentity.tls.certresolver=myresolver"
        - "traefik.http.services.sidentity.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.sidentity-headers.headers.customrequestheaders.X-Forwarded-Host=suser.i-myapp.com"
      networks:
        - Sultan_network
      restart: always
    
    
    
    
    
    
    
    
    # ------------------------
  # END
  # ------------------------   

secrets:
  app_secrets:
    file: /opt/infra/secrets/app_secrets.env
networks:
  NSY_network:
    external: true
  Sultan_network:
    external: true




#Server=161.97.185.223